#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clinfo
Version  : 2.2.17.06.14
Release  : 5
URL      : https://github.com/Oblomov/clinfo/archive/2.2.17.06.14.tar.gz
Source0  : https://github.com/Oblomov/clinfo/archive/2.2.17.06.14.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 Public-Domain
Requires: clinfo-bin
BuildRequires : beignet-dev
BuildRequires : pkgconfig(OpenCL)
Patch1: build.patch

%description
A simple OpenCL application that enumerates all possible platform and
device properties. Inspired by AMD's program of the same name, it is
coded in pure C99 and it tries to output all possible information,
including that provided by platform-specific extensions, and not to
crash on platform-unsupported properties (e.g. 1.2 properties on 1.1
platforms).

%package bin
Summary: bin components for the clinfo package.
Group: Binaries

%description bin
bin components for the clinfo package.


%prep
%setup -q -n clinfo-2.2.17.06.14
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1499272998
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1499272998
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clinfo
